@ShoppingList.Server_HostAddress = https://localhost:64099

GET {{ShoppingList.Server_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{ShoppingList.Server_HostAddress}}/api/{controller}
Content-Type: application/json

{
  "Title": "Tester"
}

###

@id=0
GET {{ShoppingList.Server_HostAddress}}/api/{controller}/{{id}}

###
